/**
 * Relay creation — prepare one delivery of RSM context.
 *
 * `createRelay` is the domain entry point for every delivery (both automatic
 * interactions and manual Replay). It:
 *  1. Checks the fail-closed authorization gate.
 *  2. Builds the Replay envelope from the selected bucket.
 *  3. Returns a `PreparedRelay` { relay, envelope } ready for streaming.
 *
 * Pure TypeScript. Zero React/Vite/Supabase/AI imports.
 */

import { RsmError } from "../errors";
import { getDefaultHasher, randomUuid, type Hasher } from "../crypto/hash";
import type { Bucket } from "../bucket/types";
import {
  createReplayEnvelope,
  isReplayable,
  DEFAULT_REPLAY_STATES,
  type ReplayEnvelope,
} from "../replay/envelope";
import { canDeliver, type GateResult } from "./gate";
import { RELAY_STATES, type Conversation, type Relay, type RelaySnapshot } from "./types";

export interface CreateRelayOptions {
  /** Override relay_id (auto-generated by default). */
  relayId?: string;
  /** Override creation timestamp (ISO-8601 UTC; default = now). */
  at?: string;
  /** Hasher for envelope sealing (default = system hasher). */
  hasher?: Hasher;
}

/** Outcome of a successful relay creation: the relay record + the prepared envelope (for streaming). */
export interface PreparedRelay {
  relay: Relay;
  envelope: ReplayEnvelope;
  gate: GateResult & { ok: true };
}

/** Reason for a refused delivery — exposed to the UI via the hook. */
export interface DeliveryRefusal {
  ok: false;
  gate: GateResult & { ok: false };
}

/**
 * Create a relay for one delivery. Validates the gate, builds the envelope,
 * and returns the prepared relay + envelope ready for streaming.
 *
 * @throws {RsmError} with code VALIDATION_ERROR when the gate refuses or the
 *                    bucket is not replayable.
 */
export async function createRelay(
  conversation: Conversation,
  bucket: Bucket,
  options: CreateRelayOptions = {},
): Promise<PreparedRelay> {
  const gate = canDeliver(conversation, bucket.bucket_id);
  if (!gate.ok) {
    throw new RsmError("VALIDATION_ERROR", `Delivery refused (${gate.code}): ${gate.message}`);
  }

  // Safety check: only replayable-state buckets may be delivered.
  const states = [...DEFAULT_REPLAY_STATES];
  if (!isReplayable(bucket, states)) {
    throw new RsmError(
      "VALIDATION_ERROR",
      `Bucket ${bucket.bucket_id} is in state "${bucket.lifecycle_state}" and is not eligible for delivery. ` +
        `Only ${states.join("/")} buckets may be replayed.`,
    );
  }

  const hasher = options.hasher ?? getDefaultHasher();
  const envelope = await createReplayEnvelope([bucket], {
    replayId: options.relayId,
    at: options.at,
    hasher,
    states,
  });

  const now = options.at ?? new Date().toISOString();
  const snapshot: RelaySnapshot = {
    envelope_ref: envelope.replay_id,
    envelope_hash: envelope.envelope_hash,
    states: [...states],
  };

  const relay: Relay = {
    relay_id: envelope.replay_id,
    conversation_id: conversation.conversation_id,
    bucket_ids: [bucket.bucket_id],
    snapshot,
    state: RELAY_STATES.Preparing,
    created_at: now,
    streamed_at: null,
    error: null,
  };

  return { relay, envelope, gate: gate as GateResult & { ok: true } };
}
